### ISSUE TITLE
newrelic-bundle-nri-metadata-injection-job failed

### ISSUE THREAD

**Issue by panho66** [newrelic/k8s-webhook-cert-manager#40]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )
newrelic-bundle-nri-metadata-injection-job failed to locate certificate approved.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen. )
Certificate approved. 
./generate_certificate.sh script able to find approved certificate

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )
**<h3>container log:</h3>**
creating certs in tmpdir /tmp/tmp.cJcAIl
Generating RSA private key, 2048 bit long modulus (2 primes)
................................................................................................................................................................................................+++++
..........+++++
e is 65537 (0x010001)
creating csr: newrelic-bundle-nri-metadata-injection.master
Error from server (NotFound): certificatesigningrequests.certificates.k8s.io "newrelic-bundle-nri-metadata-injection.master" not found
certificatesigningrequest.certificates.k8s.io/newrelic-bundle-nri-metadata-injection.master created
NAME                                            AGE   SIGNERNAME                     REQUESTOR                                                             CONDITION
newrelic-bundle-nri-metadata-injection.master   0s    kubernetes.io/legacy-unknown   system:serviceaccount:master:newrelic-bundle-nri-metadata-injection   Pending
certificatesigningrequest.certificates.k8s.io/newrelic-bundle-nri-metadata-injection.master approved
ERROR: After approving csr newrelic-bundle-nri-metadata-injection.master, the signed certificate did not appear on the resource. Giving up after 1 minute.

**<h3>kubectl command</h3>**
kubectl get certificatesigningrequests.v1beta1.certificates.k8s.io/nri-bundle-nri-metadata-injection.master
NAME                                       AGE     SIGNERNAME                     REQUESTOR      CONDITION
nri-bundle-nri-metadata-injection.master   5m50s   kubernetes.io/legacy-unknown   u-34muy35xxv   Approved

**<h3>kubectl command</h3>**
kubectl get certificatesigningrequests.v1beta1.certificates.k8s.io/nri-bundle-nri-metadata-injection.master -o json

{
    "apiVersion": "certificates.k8s.io/v1beta1",
    "kind": "CertificateSigningRequest",
    "metadata": {
        "creationTimestamp": "2021-02-12T12:26:03Z"

     deleted  
 
    }
    "status": {
        "conditions": [
            {
                "lastTransitionTime": "2021-02-12T12:26:03Z",
                "lastUpdateTime": "2021-02-12T12:26:03Z",
                "message": "This CSR was approved by kubectl certificate approve.",
                "reason": "KubectlApprove",
                "status": "True",
                "type": "Approved"
            }
        ]
    }
}

**<h3>script failed to find approved certificate </h3>**
verify certificate has been signed
i=1
while [ "$i" -ne 20 ]
do
  serverCert=$(kubectl get "${csr}/${csrName}" -o jsonpath='{.status.certificate}')
  if [ "${serverCert}" != '' ]; then
      break
  fi
  sleep 10
  i=$((i + 1))
done

**<h3>kubectl command</h3>**
kubectl get  node -o wide
NAME    STATUS   ROLES                      AGE     VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                                      KERNEL-VERSION                CONTAINER-RUNTIME
xxxx1   Ready    controlplane,etcd,worker   3h48m   v1.19.7   10.97.13.191   <none>        Red Hat Enterprise Linux Server 7.9 (Maipo)   3.10.0-1160.15.2.el7.x86_64   docker://1.13.1

**<h3>kubectl command</h3>**
kubectl get certificatesigningrequests.v1beta1.certificates.k8s.io/nri-bundle-nri-metadata-injection.master
NAME                                       AGE   SIGNERNAME                     REQUESTOR      CONDITION
nri-bundle-nri-metadata-injection.master   37m   kubernetes.io/legacy-unknown   u-34muy35xxv   Approved
 
**<h3>kubectl command</h3>** 
kubectl get certificatesigningrequests.v1beta1.certificates.k8s.io/nri-bundle-nri-metadata-injection.master -o 'jsonpath={.status.certificate}'
 

kubectl get certificatesigningrequests.v1beta1.certificates.k8s.io/nri-bundle-nri-metadata-injection.master -o 'jsonpath={.status.conditions[0].status}'
True 

## Steps to Reproduce
[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )
helm repo add newrelic https://helm-charts.newrelic.com

helm install newrelic-bundle newrelic/nri-bundle \
 --set global.licenseKey=LICENCE_KEY\
 --set global.cluster=mycluster\
 --namespace=master \
 --set newrelic-infrastructure.privileged=true \
 --set ksm.enabled=true \
 --set kubeEvents.enabled=true \
 --set logging.enabled=true 

## Your Environment
[TIP]:  # ( Include as many relevant details about your environment as possible including the running version of New Relic software and any relevant configurations. )
Rancher 2.5.5
v1.19.7 
Red Hat Enterprise Linux Server 7.9 
docker 1.13.1

## Additional context
[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by panho66** [comment]
found out the problem.
Rancher created K8s do not have certificate signing enabled.

services:
  kube-controller: 
    extra_args: 
      cluster-signing-cert-file: "/etc/kubernetes/ssl/kube-ca.pem"
      cluster-signing-key-file: "/etc/kubernetes/ssl/kube-ca-key.pem"

**Comment by bootsie123** [comment]
Hi! I'm having the same issue. Did you manage to find a solution to this?
